### ISSUE TITLE
[错误] 系统更新后 无法获取web控制平台

### ISSUE THREAD

**Issue by maliming123** [glider0/ranga-bugtracker#2]
采用什么设备（你可以在 Web 控制台“关于 Ranga” 中获取）：K2

系统版本号（你可以在 Web 控制台“关于 Ranga” 中获取）：4.1.2

清楚具体的描述问题（见 README 的例子）：
系统更新后，提示刷新页面，ctrl+ f5刷新后  提示登录山东移动高校宽带网  在登陆192.168.1.1无法登陆
如果需要，日志

日志中可能包含你的敏感信息，请务必脱敏处理！但不要让脱敏破坏日志中的其他信息或结构！
例如，你可以将 `178xxxxxxxx` 全局替换为 `<MY_PPPOE_USERNAME>`

```
在这里粘贴日志
```

**Comment by glider0** [comment]
你的系统版本是 4.1.2，你更新了 4.1.3 版本是一个完整包更新。

完整包更新页面对此有详细说明：https://glider0.github.io/updates/ranga.html

> 为你的设备下载更新，然后前往 Web 控制台或者使用命令行工具更新，随后，设备将很快重启，请耐心等待设备重启完毕，绝对不可以切断电源，然后，等待电源指示灯不在闪烁后，你必须使用网线连接到设备，因为 Wi-Fi 默认不会开启。然后打开 http://192.168.1.1/cgi-bin/act，按提示进行操作，再经过一次很快的重启，你就可以进入 http://192.168.1.1/ 打开设置向导了！你可以直接跳过设置向导，也可以通过设置向导完成基本设置。

请转到  http://192.168.1.1/cgi-bin/act 继续操作
