### ISSUE TITLE
[错误] windows客户端更新 Ranga问题

### ISSUE THREAD

**Issue by dududulu** [glider0/ranga-bugtracker#4]
**采用什么设备（你可以在 Web 控制台“关于 Ranga” 中获取）：HuaWei HG255D (OHE)**

**系统版本号（你可以在 Web 控制台“关于 Ranga” 中获取）：3.5.x**

**清楚具体的描述问题（见 README 的例子）：客户端刷入固件显示没有权限（保证超级用户密码输入正确），客户端显示：You don't have permission to access /cgi-bin/nswa-upgrade.sh?a=patch&b=admin123&c= on this server.**

**Comment by glider0** [comment]
这是第一批发布版本的缺陷，很抱歉你需要送回设备进行更新。

NSWA 的升级接口经过了数次变更。

rsync
NSWA-push
NSWA-upgrade 0.99
NSWA-upgrade 1.0 1.1 （NSWA 3.4 - NSWA 3.8.5）
NSWA-upgrade 2.0 （NSWA 3.8.5 - NSWA Ranga 最新版）

NSWA 3 legacy 系列使用的是 0.99（后来发现的 1.0 的缺陷版本），因此导致现有升级工具无法正确升级。现在制作的升级工具（复刻版）只能兼容 NSWA 3B 系列的旧协议。

很抱歉给你带来此问题，legacy 系列用户的免费升级服务将会无限延长。你随时都可以送回设备进行升级。

另外，我们还在进行 HuaWei HG255D 换新优惠政策，请参考官方 QQ 群组。
